# Generated by Django 6.0.1 on 2026-02-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow_app', '0003_meetingsession_onlineuser_useractivity_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='animations_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='color_theme',
            field=models.CharField(choices=[('blue', 'Blue (Default)'), ('purple', 'Purple'), ('green', 'Green'), ('red', 'Red'), ('dark-blue', 'Dark Blue'), ('dark-purple', 'Dark Purple'), ('dark-green', 'Dark Green'), ('dark-red', 'Dark Red')], default='blue', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('x-large', 'Extra Large')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_color',
            field=models.CharField(default='#7c3aed', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (Follow system)')], default='light', max_length=20),
        ),
    ]
