# Generated by Django 4.2 on 2026-02-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crow_app', '0003_userprofile_animations_enabled_and_more'),
        ('crow_app', '0004_userprofile_animations_enabled_and_more'),
    ]

    operations = [
    ]
